graph TD
postMessageWithContentHeight --> delayShowChallengeData
delayShowChallengeData --> setRunStatus
setRunStatus --> handleMobile
handleMobile --> handleWeb
handleWeb --> setRunStatus
setRunStatus --> setRunStatus